### PR TITLE
Solved a serious performance issue

### PR DESCRIPTION
**Pull request by darzid**
I noticed that processing 75 MB WAV files (like 10 or so) took forever (minutes). 
Diving deeper it proved to be the check that prevents duplicate additional fields in MetaDataIO.cs. These 2 calls (.Contains() + .Remove()) took 95% CPU time.

I've added a boolean to enable/disable this check for now, so you can easily test the behavior. Setting it to true should bring back the performance problem. If you cannot reproduce the issue, then it must be file related. In that case I can send you an example WAV file.  

PS: I'm a seasoned developer (well, Solution Architect nowadays), and know my way around Azure DevOps, but this is my first submission on GitHub. So I hope I'm doing this the right way :)

### CODE REVIEW

**Comment by darzid** [comment]
It might help to have some exact numbers :) 

With the duplicate check bypassed:
Processing 180 files takes 5.7 seconds

With the check enabled:
Processing 1 file takes 5 seconds
Processing 5 files takes 27 seconds
Etc.

**Comment by Zeugma440** [comment]
Hi and thanks for your feedback 😄 

You definitely pointed to something that needs to be fixed. However I can't repro it without more details. You see, I just tested reading a 110MB WAV file without any performance issue.

Coud you tell me :
  - What do you mean by "processing" ? Could you provide the code you're using ?
  - Could you also upload one of these WAV files so that I can be in the exact same conditions as yours ?
  - Last but not least, on which framework are you running the library ? Mono ? .NET Core ? .NET Standard ? .NET Framework ? Which version ?

Thanks in advance~

**Comment by darzid** [comment]
Hi!

Processing:
I just iterate over a bunch of FileInfos, which can be aiff, wav, flac or MP3. It fails (at least) with WAV.
Then I just create a ATL Track object, get some key fields, and that’s it. See below
public void LoadTrackMetadata()
{
       Track trackMetadata = new Track(this.FileInfo.FullName);
this.TrackInfoFromMetadata =
              new TrackInfo(
                     "Metadata",
                     trackMetadata.TrackNumber,
                     trackMetadata.Artist,
                     trackMetadata.Title,
                     trackMetadata.Album,
                     trackMetadata.AlbumArtist,
                     trackMetadata.Year);
       _trackInfos.Add(this.TrackInfoFromMetadata);
}

Example WAV:
https://1drv.ms/u/s!AptO6CsSFw6MrfkaOVqUW-jDYToRwA?e=pHexCH
Pwd: 123456ab!

Running this single file with the check enabled takes somewhere from 2.5 - 3.5 seconds:
[cid:image001.png@01D68547.4B783670]

Running it without takes 0.21 seconds

[cid:image003.png@01D68547.4B783670]

Platform:
My app is a .NET Framework 4.8 WPF App.


I hope you can recreate the issue with my WAV file. If you need more info, let me know!

Regards,

Steven

**Comment by Zeugma440** [comment]
The flame graph hast spoken... and you're totally right, there's definitely something going on there 🤔 

image

**Comment by darzid** [comment]
Yeah, I found it by using Visual Studio’s Diagnostic Tools with the CPU profiler…

The .Contains() used about 53% of the CPU time, and the .Remove() used about 40% of the CPU time 😀😀😀.

That seemed like a tad much for iterating through a bunch of metadata

[cid:image002.png@01D68561.62925F10]

**Comment by Zeugma440** [comment]
Final word was the LIST/INFO field had a frame I didn't expect, which caused the parser to iterate waaay more than it should have. It's all fixed now (see 4867ea10b580174de2c3447b7b9372770915c723)

The fix will be published in the next release. I'm still working on Audible support, so it might take a few more days :)

**Comment by darzid** [comment]
Nice!!!

**Comment by Zeugma440** [comment]
@darzid the fix is out today with v1.10. Enjoy~

**Comment by darzid** [comment]
Hi there!!!!

After a pause I’ve been working on my Music Info Finder tool again, and today I ran into a new issue within your ATL library.

I hadn’t switched to the latest version before, but after running into an exception when updating/saving metadata I got the latest version from Github. But unfortunately, the exception still occurs.

These are the metadata fields I’m setting on this WAV file:

  *   TrackNumber = 1
  *   Artist = “Ace Ventura”
  *   Title = “Going Back”
  *   Album = “Paradise Engineering”
  *   AlbumArtist = “Ace Ventura”
  *   Year = 2015
  *   Genre = “Psychedelic Trance”

And I’m also adding an embedded JPEG:
using (var streamReader = copiedAudioFile.FileSystem.File.OpenRead(Path.Combine(outputDirectory, "album.jpg")))
{
       byte[] buffer = new byte[streamReader.Length];
       int bytesRead = streamReader.Read(buffer);

       PictureInfo pictureInfo = PictureInfo.fromBinaryData(buffer);
       trackMetadata.EmbeddedPictures.Clear();
       trackMetadata.EmbeddedPictures.Add(pictureInfo);
}

I’ve processed hundreds of (WAV) files, all with the same code, without errors. So there must be something in this particular WAV that’s different than in the other files. But I can’t determine what.
The original file doesn’t seem to contain any (noticable) metadata, but as an additional test I’ve just tried to clear all “AdditionalFields” before updating it with my metadata. That doesn’t resolve the issue as well.

Any clue where I should look / debug? If I can fix it, then I’ll submit a change.




“Token StartElement in state EndRootElement would result in an invalid XML document. Make sure that the ConformanceLevel setting is set to ConformanceLevel.Fragment or ConformanceLevel.Auto if you want to write an XML fragment.”

   at System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition(Token token, State currentState)
   at System.Xml.XmlWellFormedWriter.AdvanceState(Token token)
   at System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   at System.Xml.XmlWriter.WriteStartElement(String localName)
   at ATL.AudioData.IO.IXmlTag.ToStream(BinaryWriter w, Boolean isLittleEndian, MetaDataIO meta) in C:\Repos\Github\atldotnet\ATL\AudioData\IO\Helpers\IXmlTag.cs:line 152
   at ATL.AudioData.IO.WAV.write(TagData tag, BinaryWriter w, String zone) in C:\Repos\Github\atldotnet\ATL\AudioData\IO\WAV.cs:line 467
   at ATL.AudioData.IO.MetaDataIO.writeAdapter(BinaryWriter w, TagData tag, Zone zone) in C:\Repos\Github\atldotnet\ATL\AudioData\MetaDataIO.cs:line 686
   at ATL.AudioData.IO.FileSurgeon.RewriteZones(BinaryWriter fullScopeWriter, WriteDelegate write, ICollection`1 zones, TagData dataToWrite, Boolean tagExists, Boolean useBuffer) in C:\Repos\Github\atldotnet\ATL\AudioData\Utils\FileSurgeon.cs:line 227
   at ATL.AudioData.IO.FileSurgeon.RewriteZones(BinaryWriter w, WriteDelegate write, ICollection`1 zones, TagData dataToWrite, Boolean tagExists) in C:\Repos\Github\atldotnet\ATL\AudioData\Utils\FileSurgeon.cs:line 138
   at ATL.AudioData.IO.MetaDataIO.Write(BinaryReader r, BinaryWriter w, TagData tag, IProgress`1 writeProgress) in C:\Repos\Github\atldotnet\ATL\AudioData\MetaDataIO.cs:line 756
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, Int32 tagType) in C:\Repos\Github\atldotnet\ATL\AudioData\AudioDataManager.cs:line 253

**Comment by Zeugma440** [comment]
Pretty please, don't reply to a closed isssue with a new, unrelated problem

I've opened #81; please follow that new issue.

**Comment by darzid** [comment]
Sorry, you’re completely right (and with 25 years of dev experience I know, and should have done that)…
I will check that issue.

Again, sorry….Sometimes the reply button is just to easy.

**Pull request closed without merging**
