### PR TITLE
LyricsPhrase - Return true for equals if a and b are null

### PR DESCRIPTION
**Pull request by nlogozzo**
Fixes the issue where:
```csharp
LyricsPhrase? x = null;
var y = x == null;
//y would be false
```

### CODE REVIEW

**Comment by Zeugma440** [comment]
CodeCov says some of the new code isn't covered.

Could you please add the corresponding unit tests?

https://github.com/Zeugma440/atldotnet/blob/main/ATL.unit-test/Misc/LyricsSortTest.cs

Thanks~

**Comment by nlogozzo** [comment]
> Could you please add the corresponding unit tests?

I have no experience with tests but I think I did it right 😅

**Comment by Zeugma440** [comment]
Indeed, what you added looks good. However, there's still an uncovered part of the code that looks fishy

image

Wouldn't that produce `null != null`? Are you certain that's what you want to acheive?

**Comment by nlogozzo** [comment]
> Wouldn't that produce null != null? Are you certain that's what you want to acheive?

Ah you're right...fixed :)

**Comment by Zeugma440** [comment]
Looks fine! Thanks for your contribution 😄

**Comment by Zeugma440** [comment]
Available on today's v5.07

**Pull request merged**
